CREATE TABLE IF NOT EXISTS users_traits
(site_id VARCHAR(256) NOT NULL,
 user_id VARCHAR(256) NOT NULL,
 address VARCHAR(256) NULL,
 city VARCHAR(100) NULL,
 country_code VARCHAR(5) NULL,
 postal_code CHAR(5) NULL,
 state VARCHAR(50) NULL,
 age SMALLINT NULL,
 avatar_url VARCHAR(256) NULL,
 birthday DATE NULL,
 description VARCHAR(256) NULL,
 email VARCHAR(100) NULL,
 full_name VARCHAR(150) NULL,
 gender CHAR(1) NULL,
 phone VARCHAR(20) NULL,
 title VARCHAR(150) NULL,
 username VARCHAR(50) NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP NULL,
 PRIMARY KEY (site_id, user_id),
 FOREIGN KEY (user_id) REFERENCES users(user_id) ON UPDATE CASCADE,
 FOREIGN KEY (site_id) REFERENCES sites(site_id) ON DELETE CASCADE);
