CREATE TABLE IF NOT EXISTS sites
(site_id VARCHAR(256) NOT NULL,
 site_name VARCHAR(256) NOT NULL,
 site_description VARCHAR(256) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (site_id));
