CREATE TABLE IF NOT EXISTS sites_domains
(id BIGINT AUTO_INCREMENT,
 site_id VARCHAR(256) NOT NULL,
 domain_name VARCHAR(256) NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (id),
 FOREIGN KEY (site_id) REFERENCES sites(site_id) ON DELETE CASCADE);
